name: catcher
description: Plugin for error catching. Allows handling errors when they're not catched by developer. Plugin provides multiple handlers for errors.
version: 0.5.0-nullsafety.0
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
     sdk: flutter
  fluttertoast: ^8.0.0-nullsafety.0
  device_info: ^2.0.0-nullsafety.2
  package_info: ^0.5.0-nullsafety
  mailer: ^3.3.0
  dio: ^3.0.10
  flutter_mailer: ^1.0.0
  logging: ^0.11.4
  sentry: ^4.0.0

dev_dependencies:
  lint: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CatcherWeb
        fileName: core/catcher_web.dart
      android:
        package: com.jhomlala.catcher
        pluginClass: Catcher
      ios:
        pluginClass: Catcher
